function Hd = filter_hd
%FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 06-Apr-2018 13:10:45

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

N    = 500;      % Order
Fc   = 10;       % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 0.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]

t = 0:0.01:4*pi;
f0 = 1;
x = cos (2*pi*f0*t);
figure;
plot(t, x); %исходный сигнал

x_noise = awgn (x, 12);
figure;
plot (t, x_noise); %зашумленный сигнал

figure;
plot (t, abs(fft(x_noise))); %спектр сигнала

%fdatool -> создание фильтра

y = filter(Hd, x_noise);
figure;
plot (t, y);
end
